/*
* Project Euler Problem 2:
*  
* Each new term in the Fibonacci sequence is generated by adding the previous 
* two terms. By starting with 1 and 2, the first 10 terms will be:
*  
* 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
* 
* By considering the terms in the Fibonacci sequence whose values do not 
* exceed four million, find the sum of the even-valued terms.
*/

#include <stdio.h>

int main (void) {

    long int total = 0;
    long int i = 1;
    long int j = 2;
    long int tmp;

    while (j < 4000000) {
    	if (j % 2 == 0) total += j;
    	tmp = i + j;
    	i = j;
    	j = tmp;
	}

    printf("%ld\n", total);

    return 0;
}
